# SR-11408

EXCEPTION! A task was canceled.
Exception Type: System.Threading.Tasks.TaskCanceledException
Stack trace at MiX.Core.Retries.ElasticRetryStrategy.ShouldRetry(String callerMemberName, String callerFilePath, Int32 callerLineNumber) in D:\b\1\_work\990\s\MiX.Core\Retries\ElasticRetryStrategy.cs:line 110
at MiX.Core.Retries.RetryStrategy.<ExitRetryAsync>d__33.MoveNext() in D:\b\1\_work\990\s\MiX.Core\Retries\RetryStrategy.cs:line 362
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MiX.Core.Retries.RetryStrategy.<ExecuteActionWithTraceAsync>d__25.MoveNext() in D:\b\1\_work\990\s\MiX.Core\Retries\RetryStrategy.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MiX.Core.Clients.HttpRetries.<ExecuteAsync>d__13.MoveNext() in D:\b\1\_work\990\s\MiX.Core\Clients\HttpRetries.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MiX.Core.Clients.HttpRetries.<Execute>d__12.MoveNext() in D:\b\1\_work\990\s\MiX.Core\Clients\HttpRetries.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MiX.DeviceConfig.Api.Client.Repositories.MobileUnitRepository.<DecommissionStreamax>d__79.MoveNext() in D:\b\1\_work\1003\s\MiX.DeviceConfig.Api.Client\Repositories\MobileUnitRepository.cs:line 1009

--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

at DynaMiX.Api.NancyModules.FleetAdmin.Assets.AssetCommissioningModule.UpdateAssetCommissioning(String authToken, Int64 orgId, Int64 assetId, AssetCommissioningFormCarrier carrier) in D:\b\1\_work\1301\s\API\DynaMiX.API\NancyModules\FleetAdmin\Assets\AssetCommissioningModule.cs:line 1210
at DynaMiX.Api.NancyModules.FleetAdmin.Assets.AssetCommissioningModule.<.ctor>b__19_2(Object args) in D:\b\1\_work\1301\s\API\DynaMiX.API\NancyModules\FleetAdmin\Assets\AssetCommissioningModule.cs:line 158

at DynaMiX.Core.Http.Nancy.ModuleBase.<>c__DisplayClass46_0`1.<RegisterRoute>b__2(Object args) in D:\b\1\_work\1301\s\Core\DynaMiX.Core.Http\Nancy\ModuleBase.cs:line 501
at DynaMiX.Core.Http.Nancy.ModuleBase.<>c__DisplayClass27_1`1.<HandleTyped>b__1() in D:\b\1\_work\1301\s\Core\DynaMiX.Core.Http\Nancy\ModuleBase.cs:line 287
at DynaMiX.Core.Http.Nancy.ModuleBase.ProcessTypedResponse[T](Func`1 method) in D:\b\1\_work\1301\s\Core\DynaMiX.Core.Http\Nancy\ModuleBase.cs:line 214
at DynaMiX.Core.Http.Nancy.ModuleBase.HandledTypedResponse[T](Func`1 method) in D:\b\1\_work\1301\s\Core\DynaMiX.Core.Http\Nancy\ModuleBase.cs:line 148